apiVersion: v1
kind: Service # this is basically a proxy configuration to route connections to pods
metadata:
  name: utilities
spec:
  selector:
    run: utilities # will match pods with this label
  ports:
  - port: 5004 # the service listen on
    targetPort: 5004 # the pods listen on
