
---
- name: Deploy Firecrest
  gather_facts: No
  hosts: all
  vars:
    firecrest_dir: "/home/centos/firecrest"

  tasks:

    - name: create firecrest directory
      file:
        path: "{{ firecrest_dir }}"
        state: directory
        owner: centos
        group: centos
        mode: "0755"

    - name: Clone firecrest git repository
      git:
        repo: "https://github.com/eth-cscs/firecrest.git"
        dest: "{{ firecrest_dir }}"
        version: "{{ commit_id }}"

    - name: Create containers network
      community.general.docker_network:
        name: firecrest-internal
        driver: "bridge"
        ipam_config:
          - subnet: "192.168.220.0/24"

    - name: Taskpersistence
      community.general.docker_container:
        name: taskpersistence
        #image: "{{ docker_registry_host }}/taskpersistence:{{commit_id}}"
        image: "redis:5"
        volumes:
          - "{{ firecrest_dir }}/deploy/demo/taskpersistence/redis.conf:/redis.conf:ro"
          - "{{ firecrest_dir }}/deploy/demo/taskpersistence-data:/data:delegated"
          - "{{ firecrest_dir }}/deploy/demo/logs:/var/log:delegated"
        networks:
              - name: firecrest-internal
                ipv4_address: "192.168.220.13"

    - name: Tasks
      community.general.docker_container:
        name: tasks
        image: "{{ docker_registry_host }}/tasks:{{commit_id}}"
        env_file: "{{ firecrest_dir }}/src/deploy/demo/common/common.env"
        env:
          F7T_PERSIST_PORT: "6379"
          F7T_PERSIST_PWD: "rediS2200"
          F7T_DEBUG_MODE: "True"
          F7T_COMPUTE_TASK_EXP_TIME: "86400"
          F7T_STORAGE_TASK_EXP_TIME: "2678400"
        volumes:
          - "{{ firecrest_dir }}/deploy/demo/logs/firecrest:/var/log:delegated"
        networks:
              - name: firecrest-internal
                ipv4_address: "192.168.220.6"
