apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: f7t-certificator-svc
  spec:
    type: ClusterIP
    selector:
      app: certificator-opa
    ports:
    - name: "8181"
      protocol: TCP
      port: 8181
      targetPort: 8181
    - name: "5010"
      port: TCP
      port: 5010
      targetPort: 5010
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: certificator-opa
  spec:
    selector:
      matchLabels:
        app: certificator-opa
    template:
      metadata:
        labels:
          app: certificator-opa
      spec:
        nodeSelector:
          kubernetes.io/hostname: starlex3 #so it is deployed in here
        containers:
        - name: f7t-opa
          image: openpolicyagent/opa:0.22.0
          args: ["run", "--server", "--log-level=debug", "--log-format=json-pretty", "/opa-files/data.json", "/opa-files/policy.rego"]
          ports:
          - containerPort: 8181
          volumeMounts:
          - mountPath: /opa-files/
            name: f7t-opa-vol
        - name: f7t-certificador
          image: 148.187.97.229:5000/certificator:k8s-training
          ports:
          - containerPort: 5010
          envFrom:
            - configMapRef:
                name: common-env-file        
          volumeMounts:
          - mountPath: /ca-key #since ConfiMap mount
            name: f7t-cert-vol                    
            subPath: ca-key
          - mountPath: /user-key.pub
            name: f7t-cert-user-pub-vol               
            subPath: user-key.pub
        volumes:
        - name: f7t-opa-vol
          configMap:
            name: f7t-opa-configmap
        - name: f7t-cert-vol
          configMap:
            name: f7t-ca-ssh-keys 
            defaultMode: 0400
        - name: f7t-cert-user-pub-vol
          configMap:
            name: f7t-user-ssh-pub-keys            
kind: List
