apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-kong
    namespace: firecrest
  spec:
    # type: NodePort
    selector:
      app: kong
    ports:
    - name: "8000"
      port: 8000
      targetPort: 8000      
  status:
    loadBalancer: {}
kind: List
