apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy-cluster
  spec:
    selector:
      matchLabels:
        app: cluster
    template:
      metadata:
        labels:
          app: cluster
      spec:
        hostname: cluster
        containers:
        - name: f7t-cluster
          image: localhost:32000/cluster:k8s
          imagePullPolicy: Always
          ports:
          - containerPort: 22
kind: List
