apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: f7t-cluster-svc
  spec:
    type: ClusterIP
    selector:
      app: f7t-cluster
    ports:
    - name: "22"
      protocol: TCP
      port: 22
      targetPort: 22
kind: List
