apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yaml -o f7t_keycloak.yaml
      kompose.version: 1.1.0 (36652f6)
    creationTimestamp: null
    labels:
      io.kompose.service: keycloak
    name: keycloak
  spec:
    ports:
    - name: "28080"
      port: 28080
      targetPort: 8080
    selector:
      io.kompose.service: keycloak
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yaml -o f7t_keycloak.yaml
      kompose.version: 1.1.0 (36652f6)
    creationTimestamp: null
    labels:
      io.kompose.service: keycloak
    name: keycloak
  spec:
    replicas: 1
    strategy: {}
    selector:
      matchLabels:
        io.kompose.service: keycloak
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: keycloak
      spec:
        nodeSelector: 
          kubernetes.io/hostname: starlex3
        containers:
        - image: jboss/keycloak:4.8.3.Final
          env:
          - name: DB_VENDOR
            value: H2
          - name: DIR_DATA
            value: /var/tmp
          - name: Dkeycloak.migration.realmName
            value: kcrealm
          - name: KC_REALM_DISPLAY_NAME
            value: kcrealm
          - name: KC_REALM_NAME
            value: kcrealm
          - name: KEYCLOAK_IMPORT
            value: /var/tmp/config.json
          - name: KEYCLOAK_PASSWORD
            value: admin2
          - name: KEYCLOAK_USER
            value: admin
          name: f7t-keycloak
          ports:
          - containerPort: 8080
            hostIP: 127.0.0.1
          volumeMounts:
          - mountPath: /var/tmp/
            name: f7t-keycloak-config
          resources: {}
        volumes:
        - name: f7t-keycloak-config
          configMap:
            name: f7t-keyclok-config
#        - name: f7t-keycloak-vol
#          hostPath:
#            path: /home/shared/firecrest/keycloak/
#            type: Directory
kind: List
metadata: {}

