apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: f7t-keycloak-secret
  data:
    KEYCLOAK_PASSWORD: YWRtaW4yCg==
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: keycloak
    name: keycloak
  spec:
    type: ClusterIP
    selector:
      app: keycloak
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9990"
      port: 9990
      targetPort: 9990
    selector:
      app: keycloak
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: keycloak
    name: keycloak
  spec:
    replicas: 1
    strategy: {}
    selector:
      matchLabels:
        app: keycloak
    template:
      metadata:
        labels:
          app: keycloak
      spec:
        nodeSelector: 
          kubernetes.io/hostname: starlex3
        containers:
        - image: jboss/keycloak:4.8.3.Final
          env:
          - name: DB_VENDOR
            value: H2
          - name: DIR_DATA
            value: /var/tmp
          - name: Dkeycloak.migration.realmName
            value: kcrealm
          - name: KC_REALM_DISPLAY_NAME
            value: kcrealm
          - name: KC_REALM_NAME
            value: kcrealm
          - name: KEYCLOAK_IMPORT
            value: /var/tmp/config.json
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: f7t-keycloak-secret
                key: KEYCLOAK_PASSWORD
          - name: KEYCLOAK_USER
            value: admin
          name: f7t-keycloak
          ports:
          - containerPort: 8080
            hostIP: 127.0.0.1
          - containerPort: 9990
            hostIP: 127.0.0.1
          volumeMounts:
          - mountPath: /var/tmp/
            name: f7t-keycloak-volume
          resources: {}
        volumes:
        - name: f7t-keycloak-volume
          configMap:
            name: f7t-keycloak-configmap
kind: List
