apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: status
  template:
    metadata:
      labels:
        run: status      
    spec:
      containers:
      - image: demo_status
        imagePullPolicy: Never
        name: status
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: common-env-file
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint        
      volumes:
      - emptyDir: {}
        name: logs-endpoint      
