apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status      
    spec:
      containers:
      - image: localhost:32000/status:k8s
        imagePullPolicy: Always
        name: status
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: common-env-file
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint        
      volumes:
      - emptyDir: {}
        name: logs-endpoint      
