apiVersion: batch/v1
kind: Job
metadata:
  name: job-tester
  namespace: {{ .Values.namespace }}
spec:
#  selector:
#    matchLabels:
#      app: tester
  template:
    metadata:
      labels:
        app: tester
        role: microservice
    spec:
      containers:
      - image: "{{ .Values.registry }}/tester:{{ .Values.tag }}"
        imagePullPolicy: Always
        name: tester
        command: ['pytest']
        workingDir: {{ .Values.workingDir }}
        args: [{{ .Values.tester_args }}]
        envFrom:
        - configMapRef:
            name: common-env-file
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
      restartPolicy: Never
      {{ if .Values.registry_secret_creds }}
      imagePullSecrets:
      - name: "{{ .Values.registry_secret_creds }}"
      {{ end }}
      volumes:
      - emptyDir: {}
        name: logs-endpoint
  backoffLimit: 0
