apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-tester
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tester
  template:
    metadata:
      labels:
        app: tester
        role: microservice
    spec:
      containers:
      - image: "{{ .Values.registry }}/tester:{{ .Values.tag }}"
        imagePullPolicy: Always
        name: tester
        command:
        - pytest
        args:
        - "{{ .Values.tester_arg }}"
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
      {{ if .Values.registry_secret_creds }}
      imagePullSecrets:
      - name: "{{ .Values.registry_secret_creds }}"
      {{ end }}
      volumes:
      - emptyDir: {}
        name: logs-endpoint
