apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy-jaeger
    namespace: {{ .Values.namespace }}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jaeger
    strategy: {}
    template:
      metadata:
        labels:
          app: jaeger
      spec:
        containers:
        - image: jaegertracing/all-in-one:1.24
          env:
          - name: COLLECTOR_ZIPKIN_HOST_PORT
            value: "9411"
          name: jaeger-k8
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
