apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-openapi
    namespace: public
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      app: openapi
  status:
    loadBalancer: {}
kind: List
metadata: {}
