version: '3'
services:

  certificator:
    build: 
      context: ../../
      dockerfile: deploy/docker/certificator/Dockerfile
    env_file:
      - ./environment/common.env
    network_mode: "host"
    volumes:
      - "./environment/keys/ca-key:/ca-key"
      - "./environment/keys/user-key.pub:/user-key.pub"

  taskpersistence:
    build: 
      context: ../../
      dockerfile: deploy/test-build/taskpersistence/Dockerfile
    network_mode: "host"

  status:
    build:
      context: ../../
      dockerfile: deploy/docker/status/Dockerfile
    env_file:
      - ./environment/common.env
    network_mode: "host"

  utilities:
    build: 
      context: ../../
      dockerfile: deploy/docker/utilities/Dockerfile
    env_file:
      - ./environment/common.env
    network_mode: "host"
    volumes:
      - "./environment/keys/user-key:/user-key"

  tasks:
    build: 
      context: ../../
      dockerfile: deploy/docker/tasks/Dockerfile
    env_file:
      - ./environment/common.env
    environment:
      - PERSIST_PORT=6379 
      - PERSIST_PWD=rediS2200
      - DEBUG_MODE=True
    depends_on:
      - "taskpersistence"
    network_mode: "host"

  compute:
    build:
      context: ../../
      dockerfile: deploy/docker/compute/Dockerfile
    env_file:
      - ./environment/common.env
    network_mode: "host"
    volumes:
      - "./environment/keys/user-key:/user-key"

  cluster:
    build: 
      context: ./
      dockerfile: ./cluster/Dockerfile
    ports:
      - "2223:22"
    hostname: cluster

  storage:
    build:
      context: ../../
      dockerfile: deploy/docker/storage/Dockerfile
    env_file:
      - ./environment/common.env
      - ./environment/storage.env
    network_mode: "host"
    depends_on:
      - "tasks"
      - "minio"
    volumes:
      - "./environment/keys/user-key:/user-key"

  minio:
    image: minio/minio
    command: minio server /data
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
    environment:
     MINIO_ACCESS_KEY: storage_access_key
     MINIO_SECRET_KEY: storage_secret_key
