##
##  Copyright (c) 2019-2021, ETH Zurich. All rights reserved.
##
##  Please, refer to the LICENSE file in the root directory.
##  SPDX-License-Identifier: BSD-3-Clause
##
---
- name: Build firecrest microservices images
  hosts: all
  gather_facts: No
  roles:
    - { role: build_image_role }
