---
- name: Run tests
  gather_facts: no
  hosts: all
  vars:
    firecrest_tests_dir: "/home/centos/firecrest/src/tests/automated_tests"
  environment:
    PATH: "{{ ansible_env.PATH }}:~/.local/bin"

  tasks:
    - name: Install pytest modules
      shell: pip3 install --user -r requirements.txt
      args:
        chdir: "{{ firecrest_tests_dir }}"

    - name: Run unit tests
      shell: pytest -c demo.ini unit
      args:
        chdir: "{{ firecrest_tests_dir }}"

    - name: Run unit tests
      shell: pytest -c demo.ini unit
      args:
        chdir: "{{ firecrest_tests_dir }}"

    