---
- name: Save log files of firecrest demo deploy
  gather_facts: No
  hosts: all
  vars:
    firecrest_dir: "/home/centos/firecrest"
    logs_dest_dir: "/var/lib/awx/projects/firecrest/logs"
  
  tasks:

    - name: create firecrest logs directory in master node
      file:
        path: "{{ logs_dest_dir }}"
        state: directory
        owner: centos
        group: centos
        mode: "0755"


    # This copy log files from test server to a folder located at master node (the awx container)
    - name: fetch log files
      fetch:
        src: "{{ firecrest_dir }}/deploy/demo/logs/firecrest/{{ item }}.log"
        # dest: "/home/centos/fetched"
        dest: "{{ logs_dest_dir }}"
      register: fetch_output
      loop:
        - compute
        - utilities
        - certificator
        - status
        - tasks
        - storage

    - debug: var=fetch_output

    # Synchronizes: src an dest are folders in the remote host
    #- name: Synchronization
    #  ansible.posix.synchronize:
    #    mode: pull
    #    src: "{{ firecrest_dir }}/deploy/demo/logs/firecrest"
    #    dest: "/home/centos/tmp/"