apiVersion: v1
kind: Service # this is basically a proxy configuration to route connections to pods
metadata:
  name: svc-storage
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: storage # will match pods with this label
  ports:
  - port: 5002 # the service listen on
    targetPort: 5002 # the pods listen on
